CI housekeeping + support for Rails 8.1 (#199)
* update to ubuntu-24.04 runner as 20.04 is EOL

This requires installing PhantomJS manually, as it's no longer
included by default in the runner image. Also use solution from
openedx/edx-proctoring#1268 to get it working with Ubuntu 24.04.

Also disabled one matrix version as unsupported by ruby/setup-ruby:

    Error: Error: Unavailable version 9.2.21.0 for jruby on ubuntu-24.04
              You can request it at https://github.com/ruby/setup-ruby/issues

* fix CI errors with Rails 6.1/7.0

* simplify and document build matrix

Also use strings to avoid confusion due to YAML confusion on X.0
being treated as X.

* add Ruby 3.4 and JRuby 10.0 to CI

* support for Rails 8.1

* add CHANGELOG entry + bump version to 1.28.0